### ISSUE TITLE
Turn off optimization with lr==0.0

### ISSUE THREAD

**Issue by AngledLuffa** [facebookresearch/madgrad#16]
Is there a way to turn off optimization for a parameter group by setting lr==0.0 for that group, or via any other method?  I found that setting lr==0.0 doesn't work if eps > 0.  Would it be possible to make it so that any parameter group with lr==0.0 is skipped?

**Comment by adefazio** [comment]
Yes should be possible, I'll look into it!

**Comment by AngledLuffa** [comment]
Thanks, that would be very helpful.

I noticed this because I tried finetuning a bert model for a while, then turning off the bert finetuning by setting that to 0 and continuing to train the output layers, but the bert layers kept training because of the `eps` parameter.  (The bert layers and output layers were two separate parameter groups in my model.)

**Comment by AngledLuffa** [comment]
Thanks!
